//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTAPI
{
    using ProtoBuf;
    using System;
    using System.Collections.Generic;
    [ProtoContract]
    public partial class TICKET
    {
        [ProtoMember(1)]
        public int Id { get; set; }
        [ProtoMember(2)]
        public string Reporter { get; set; }
        [ProtoMember(3)]
        public string Message { get; set; }

        public TICKET() { }
        public TICKET(int id, string reporter, string message)
        {
            Id = id;
            Reporter = reporter;
            Message = message;
        }
    }
}
